### ISSUE TITLE
Xcode version

### ISSUE THREAD

**Issue by jonchoi** [ryendu/MusicWitHaptics#1]
Hey,

This looks cool! Would love to check it out but it doesn't build. Can you make it compatible with more versions of Xcode?

Error:
`cannot be opened because it is in a future Xcode project file format. Adjust the project format using a compatible version of Xcode to allow it to be opened by this version of Xcode.`

Seems relevant: https://stackoverflow.com/questions/49622341/failed-to-load-project-incompatible-project-version-pop-up-appears-when-i-op/50221448

**Comment by ryendu** [comment]
Oh, sorry! I forgot to take into account that I was using a beta version of Xcode! Thank you so much for bringing this up. I've just pushed a fix 😄
